Update event models to allow extra properties to ensure backwards compatibility
great-expectations/cloud pull request #130
Opened 2024-02-12 16:32 UTC by JennyTee

In #127, we are adding a property to an existing Event model. This change was made in both `mercury` and `cloud`, but we currently don't allow for extra properties on event models...so if #127 is merged and users do not immediately upgrade their GX Agent version, the RunCheckpointEvent type is not recognized and therefore cannot be processed.

To ensure backwards compatibility, we need to make sure that the Agent code can recognize events even if they have additional properties.

I'm open to doing this another way if there are suggestions.

2024-02-12 22:58 UTC, anthonyburdi approved these changes
I think this is reasonable to do for now. An alternative is to version events, but that is a much bigger lift so we should consider that separately. FYI I think you'll need to bump the version again after merging `main` since we are at 0.0.29 already.

2024-02-12 23:04 UTC, JennyTee commented
> I think this is reasonable to do for now. An alternative is to version events, but that is a much bigger lift so we should consider that separately. FYI I think you'll need to bump the version again after merging `main` since we are at 0.0.29 already.

ty @anthonyburdi! I bumped the version again.

fwiw I don't believe we currently have any tests set up to check for backwards compatibility with different versions of the Agent. Would have been easy for me to just have pushed the update to RunCheckpointEvent without manually checking for backwards compatibility. 😬 Probably something for us to consider moving forward.

2024-02-13 03:00 UTC, Kilo59 commented on great_expectations_cloud/agent/models.py
> +        extra: str = Extra.allow
Can we change this to just ignore extra fields?
```suggestion
        extra: str = Extra.ignore
```
Going from `forbid` to `allow` seems drastic.

If we start `allowing` extra fields the schema loses a lot of its value.

2024-02-13 14:59 UTC, Kilo59 commented
I would suggest creating a new event or using a FF to toggle between the new and old version of the Event.

2024-02-13 15:23 UTC, Kilo59 requested changes
I think we need to think about this more.

Even with this change users will still need to update their agent just as they would without the schema loosening.

2024-02-13 22:26 UTC, Kilo59 approved these changes

2024-02-13 22:29 UTC, JennyTee commented
> I think we need to think about this more.
> 
> Even with this change users will still need to update their agent just as they would without the schema loosening.

Sounds good. Created https://greatexpectations.atlassian.net/browse/ZEL-498 to track this; will plan on merging with `extra.ignore` per Slack convo to unblock current feature work

2024-02-13 22:30 UTC, merged