Ruff formatter
great-expectations/cloud pull request #46
Opened 2023-10-24 20:47 UTC by Kilo59

Adopt the `ruff` formatter and drop `black`

https://astral.sh/blog/the-ruff-formatter

2023-10-24 20:59 UTC, wookasz requested changes
Let's figure out which tools we'd like to use, and use them uniformly across our repositories to avoid cognitive overhead.

2023-10-24 21:09 UTC, Kilo59 commented
@wookasz 
I'm proposing that we switch to using `ruff` `format` uniformly.
Assuming no one objects and nothing unexpected pops up in the attempt to adopt it here.
Do you have a specific objection to switching to the `ruff` formatter?

Developers will likely not even notice the difference.

1. If developers have the `pre-commit` hooks installed the formatting is applied automatically when committing code.
2. If developers are using `invoke fmt` the only difference is `invoke` calls `ruff format` instead of `black`
3. If developers don't use either and misformat something the pre-commit CI will push a fix to the branch automatically.

AFAIK the only case where a developer workflow would change is if they are manually running `black` from the CLI after every change.

2023-11-13 19:25 UTC, wookasz approved these changes

2023-11-13 21:33 UTC, Kilo59 commented on poetry.lock
> +# This file is automatically @generated by Poetry 1.7.0 and should not be changed by hand.
Using a new version of `poetry` here.

2023-11-13 21:33 UTC, merged