Get view names along with tables
great-expectations/cloud pull request #498
Opened 2024-10-21 15:01 UTC by Kilo59

Return views along with table names.

https://docs.sqlalchemy.org/en/20/core/reflection.html#sqlalchemy.engine.reflection.Inspector

2024-10-25 18:00 UTC, wookasz requested changes

2024-10-25 18:00 UTC, wookasz commented on great_expectations_cloud/agent/actions/draft_datasource_config_action.py
> +    def _get_table_names(self, datasource: Datasource, *, include_views: bool) -> list[str]:
Rename to `_get_table_and_view_names` and remove the boolean flag. We don't have a need for the conditional and it makes the API less clear.

2024-10-25 18:00 UTC, wookasz commented on pyproject.toml
> +version = "20241021.0.dev0"
outdated

2024-10-25 18:00 UTC, wookasz commented on tests/agent/actions/test_draft_datasource_config.py
>      _update_table_names_list_spy.assert_called_with(config_id=config_id, table_names=table_names)
These assertions don't add any value to the test and make refactoring harder. Testing that a method calls a private helper makes no guarantee that what the helper is doing is correct.

These tests is already verifying that the correct endpoint is called with the correct tables/views and that is enough

2024-10-25 18:00 UTC, wookasz commented on tests/agent/actions/test_list_table_names_action.py
> +    inspector.get_view_names.return_value = view_names
I would expect this test to fail since we're not getting different results. The test should guarantee that we're sending back the correct results

2024-10-25 18:00 UTC, wookasz commented on tests/agent/actions/test_draft_datasource_config.py
>      _update_table_names_list_spy.assert_called_with(config_id=config_id, table_names=table_names)
Some tests here should guarantee that we return views as well

2025-01-21 16:54 UTC, tyler-hoffman commented
Stale and not tied to a ticket; closing for now.

2025-01-21 16:54 UTC, closed without merging